### ISSUE TITLE
Fix error messages for blank address

### ISSUE THREAD

**Issue by E0735389** [AY2324S2-CS2103T-T11-2/tp#103]
Currently if there's a prof and `edit 1 a/` is typed, the error message is

> Addresses can take any values, and it should not be blank

this is misleading because address in fact **can** be blank, just not for prof.

Related: #92.

**Comment by Hibeom0929** [comment]
I think it is already fixed. When I do edit 1 a/ for professor, it shows "Professors cannot have empty addresses!"

**Comment by E0735389** [comment]
Okay good
