### ISSUE TITLE
Detect duplication of name

### ISSUE THREAD

**Issue by E0735389** [AY2324S2-CS2103T-T11-2/tp#128]
Currently "`John Doe`" and "`John  Doe`" are considered distinct.

Is this behavior desirable?

**Comment by Hibeom0929** [comment]
They should be considered as a same person

**Comment by E0735389** [comment]
Be careful. Does this count as overzealous input validation?

**Comment by Hibeom0929** [comment]
It could be because although no names contain >= 2 white spaces between words, if users wrongly type someone's name with many spaces they can't edit it to the right one if we consider "John Doe" and "John  Doe" as the same name.
Then should we change the way of checking validation of name?
