### ISSUE TITLE
Mention ignoring warnings one by one in planned enhancement

### ISSUE THREAD

**Issue by Hibeom0929** [AY2324S2-CS2103T-T11-2/tp#140]
![image](https://github.com/AY2324S2-CS2103T-T11-2/tp/assets/122252489/912d6e17-a0d8-4aa2-96b6-f998731ce7d0)

For now, if there are more than two warnings, they are ignored with one f/. So that we users can't choose to ignore only the first one and fix the second one(As they might not know they make a warning).

**Comment by E0735389** [comment]
This is a valid concern (that the user does not see the second warning). Sounds like a valid planned enhancement.
