### ISSUE TITLE
Overzealous input validation for the tag

### ISSUE THREAD

**Issue by Hibeom0929** [AY2324S2-CS2103T-T11-2/tp#141]
![image](https://github.com/AY2324S2-CS2103T-T11-2/tp/assets/122252489/c11f1de5-6f71-455c-937a-3f47c2bfc32c)

Currently, tag can't have non-alphanumeric things like / ~ and also no warning.

**Comment by E0735389** [comment]
Good point. It's entirely possible for the user to want to include diacritics or Chinese characters in the tag...
