### ISSUE TITLE
[PE-D][Tester E] Minor Formatting issue in UG.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T11-2/tp#157]
It appears that `Viewing help: help` has inconsistent formatting. Perhaps you may want to look into this.

![image.png](https://raw.githubusercontent.com/tahsinhasem/ped/main/files/998c8eca-e540-40f6-8270-7420cd3fd20f.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: tahsinhasem/ped#1

**Comment by Hibeom0929** [comment]
Why is it inconsistent formatting? That line directly follows Verb + ing + noun: command format that other lines also follow.

**Comment by LargeCrowd** [comment]
I dont see a problem with this as well

**Comment by E0735389** [comment]
Good issue. The problem is I accidentally left the mouse on top of the link while printing it.

Will remember to do that next release of the UG.
