### ISSUE TITLE
[PE-D][Tester E] No definition of unambiguous prefix provided

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T11-2/tp#171]
No definition of `unambiguous prefix` provided

![image.png](https://raw.githubusercontent.com/tahsinhasem/ped/main/files/067fefbe-07bb-4337-b2c9-2f250131de6f.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: tahsinhasem/ped#5

**Comment by ChillinRage** [comment]
Note to other members. Can include a quick example of an unambiguous prefix. (Though as of now there’s no ambiguous prefix lmao).

**Comment by E0735389** [comment]
Not cosmetic (formatting) issue, just use severity.Low instead.

**Comment by Hibeom0929** [comment]
Isn't "r/s" example a quick example of unambiguous prefix?
