### ISSUE TITLE
Feature specification: how to `edit` an entry to remove its phone number?

### ISSUE THREAD

**Issue by E0735389** [AY2324S2-CS2103T-T11-2/tp#42]
We want to make phone number optional. But it's not clear how to best implement the feature.

Currently, the behavior is:
* if the user types `edit <fields>`, and `p/…` field is not specified, then the old phone number is used.
* Otherwise, the old phone number is overwritten with the new phone number.

How can the user use the `edit` command to **delete** a phone number?

* One reasonable option is to type just `p/` (empty phone number = no phone number).
* Nevertheless, if we follow this route, should we allow `p/` in `add` command (for consistency) as well? But then there are two distinct ways to not specify phone number --- namely, specify `p/`, and not specify `p/` at all.

Opinion?

**Comment by LargeCrowd** [comment]
For edit to delete: my opinion is to just put an empty space ` ` 
For add: i would think itd be easier to not specify `p/` if there is no intention to put a phone number, but regarding logic, im not sure if its more troublesome to omit `p/`

**Comment by E0735389** [comment]
> im not sure if its more troublesome to omit `p/`

We're not optimizing for simplicity in implementation here. We optimize for best-designed features.

After all, we need *something* to reach 300 lines of functional code per person.

**Comment by Hibeom0929** [comment]
I think we can follow how the "tag" part is implemented. For the tag, we can remove all the person’s tags by typing t/ without specifying any tags after it with the command edit. For add, I think we can omit it.
