### ISSUE TITLE
Allow typing an unambiguous prefix of the command to specify the command

### ISSUE THREAD

**Issue by E0735389** [AY2324S2-CS2103T-T11-2/tp#44]
e.g. the user should be able to type `a` to replace `add` (since no other command starts with `a`)

**Comment by ChillinRage** [comment]
Gotta be careful with future new commands (if we are to implement more) to ensure that no command is a prefix of another.

**Comment by E0735389** [comment]
Just have enough tests (and implement prefix detection into the code itself).
