### ISSUE TITLE
Add specific semester to course

### ISSUE THREAD

**Issue by Hibeom0929** [AY2324S2-CS2103T-T11-2/tp#47]
As every semester the students, tutor, and professor for a course are changed, it would be better to specify the semester for the courses.

**Comment by ChillinRage** [comment]
Honestly, I don't think this is necessary or desirable.
1) It adds complexity to the already long format the users have to type with.
2) It will also end up cluttering the contacts.
3) Students, generally, can remember the year and semester in which they take certain courses, so the usefulness might be limited. So the trade-off  against the added complexity and over-design might not be worth it imo.

**Comment by Hibeom0929** [comment]
As it is an individual contact list, unless a student fails a module, the student would take courses only once. So I agree with your opinions.

**Comment by ChillinRage** [comment]
~~Totally not because Idk how to efficiently code this feature without it breaking OOP~~
