### ISSUE TITLE
Should not be able to provide empty address for professor using `edit`

### ISSUE THREAD

**Issue by LargeCrowd** [AY2324S2-CS2103T-T11-2/tp#54]
Not sure how to make it such that you cannot use `edit` to delete addresses (empty input) for PROFESSORs.
Tried putting in the logic but ended up with being unable to `edit` and provide empty addresses for all roles.
Might need to access the `Role` from storage?

**Comment by E0735389** [comment]
@ChillinRage Thanks for taking. How do you intend to design the feature?
