### ISSUE TITLE
Use up arrow and down arrow to scroll through past commands

### ISSUE THREAD

**Issue by E0735389** [AY2324S2-CS2103T-T11-2/tp#77]
Just like in command-line.

(inspired from `https://github.com/AY2324S2-CS2103T-F13-3/tp/issues/53`)

**Comment by ChillinRage** [comment]
For clarification, would you all rather want the scroller to reset to the new command added, or keep the scroller in the absolute index whenever the user enters a new command?

For example, given the following command history (oldest to newest) `add ..., delete ..., find ...` and action:
I press up twice to get `delete ...` command and I press enter. (ignore the result. Now the command box is back to blank.)

Would you rather:
1. Press up again will show `delete ...`, OR
2. Press up again will show `add ...`

**Comment by E0735389** [comment]
Let's say we mimic the behavior of `bash` shell. Press up again will show the latest `delete`, and press up one more time will show `find`.

Is the behavior of Windows's cmd or PowerShell different?

By the way, bash shell also supports `ctrl+O` to focus the immediately-next command in history, but I don't think this is a very useful thing to do here (the most common use case is probably to re-edit a `edit` command that contains a typo)

**Comment by ChillinRage** [comment]
Window also resets back to latest command. I only vaguely remembered one of the systems doing the alternate version, which annoyed me alot.

**Comment by E0735389** [comment]
Then we follow that obviously.
