### ISSUE TITLE
Should not allow `edit` to give `PROFESSOR` role to Persons without `Address`

### ISSUE THREAD

**Issue by LargeCrowd** [AY2324S2-CS2103T-T11-2/tp#93]

**Comment by E0735389** [comment]
Duplicate of https://github.com/AY2324S2-CS2103T-T11-2/tp/issues/54

**Comment by LargeCrowd** [comment]
Very similar but not a duplicate. 
#54 is not allowing `edit` to give a `PROFESSOR` an empty `Address`
This one (#93) is not allowing `edit` to give a `Person` with an empty `Address` the role of `PROFESSOR`

**Comment by E0735389** [comment]
If you implement it the right way you shouldn't need special code to handle both cases. (But good to add as test cases.)
